### PR TITLE
Fixes anidb banning because of requesting the same url twice in the same day

### PR DESCRIPTION
**Pull request by soywiz**
This happens for example by reopening the application or performing the same request just after an hour

### CODE REVIEW

**Comment by soywiz** [comment]
Also I need a bit help here:

Can't resolve the `net.xeoh.jspf:jspf-core:jar:1.0.3 in https://repository-tinymediamanager.forge.cloudbees.com/release/`, any tips?

Also, is it possible to get the tinyMediaManager's `cache` folder from a scrapper? Would be nice to store the url cache there.

screenshot 2019-02-24 at 12 31 21

**Comment by mlaggner** [comment]
yes, there are some artefacts which are not mavenized...
since anidb is a rather old scraper, this has no dependency to the actual parent (which is 1.1 for now).
simply change to the actual parent in the pom.xml and the deps should be resolved fine:

```
    <parent>
        <groupId>org.tinymediamanager</groupId>
        <artifactId>tmm-parent</artifactId>
        <version>1.1</version>
    </parent>
```

we are no more developing v2 (just bugfixing) - I'd suggest you to build your fix into the scraper for v3 (over at gitlab - https://gitlab.com/tinyMediaManager/scraper/scraper-anidb)

furthermore we had a disk cache for urls which made things worse.. this is why we only cache into an LRU cache in-memory.. this will not fully solve your problems, but can avoid some duplicate calls.. 
Just switch over to the v3 version of anidb scraper and have a look at the CachedUrl there

**Comment by mlaggner** [comment]
had a look at the wiki of anidb yesterday and it is easier than I thought: the static files `http://anidb.net/api/anime-titles.dat.gz` and `http://anidb.net/api/anime-titles.xml.gz` have this limitation. So we only need to cache them for at least 24 hrs (and not every call)..
we do basically the same with the animated posters index.

we will have a look how to solve that the best way asap

**Comment by mlaggner** [comment]
I'll merge your pull request for v2.. for v3 I've implemented it differently

**Pull request merged**
